Improve logging

diff --git a/bin/rheostoick b/bin/rheostoick
--- a/bin/rheostoick
+++ b/bin/rheostoick
@@ -67,13 +67,16 @@ retval=0
 failedhooks=()
 for hook in "$hooks"/*.pre; do
 	if [[ -x "$hook" ]]; then
-		echo "Running hook: $hook" >&2
+		echo "Running hook: $hook $action $retval" >&2
 		set -o pipefail
 		"$hook" "$action" "$retval" 2>&1 | sed '1s/^/==> /; 2,$s/^/    /' >&2
 		r=$?
 		if (( r != 0 )); then
+			echo " --> Hook exit status: $r (Failure)" >&2
 			retval=$r
 			failedhooks+=("${hook##*/}")
+		else
+			echo " --> Hook exit status: $r (Success)" >&2
 		fi
 		set +o pipefail
 	fi
@@ -81,7 +84,7 @@ done
 
 # bail if a hook failed
 if (( retval != 0 )); then
-	echo "Exiting because one or more hooks signaled us to stop: ${failedhooks[*]}" >&2
+	echo " --> Exiting because one or more hooks failed: ${failedhooks[*]}" >&2
 	exit $retval
 fi
 
@@ -89,12 +92,23 @@ fi
 retval=0
 echo "Running command: restic ${!action_var}" >&2
 restic ${!action_var} || retval=$?
+echo "Ran command: restic ${!action_var}" >&2
+if (( retval != 0 )); then
+	echo " --> Restic exit status: $r (Failure)" >&2
+else
+	echo " --> Restic exit status: $r (Success)" >&2
+fi
 
 # run hooks
 for hook in "$hooks"/*.post; do
 	if [[ -x "$hook" ]]; then
-		echo "Running hook: $hook" >&2
+		echo "Running hook: $hook $action $retval" >&2
 		"$hook" "$action" "$retval" 2>&1 | sed '1s/^/==> /; 2,$s/^/    /' >&2
+		if (( $? != 0 )); then
+			echo " --> Hook exit status: $r (Failure)" >&2
+		else
+			echo " --> Hook exit status: $r (Success)" >&2
+		fi
 	fi
 done
 
